### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by artemislena** [Goctionni/KinkList#17]
T.: Would lovea fork this thing, but ya don'tve a license, so that sorta sucks :(
See https://choosealicense.com/no-permission/ why. Sth simple'd be preferred, Ig.

**Comment by Goctionni** [comment]
Hey, as far as I'm concerned it's MIT, I am working on a version 2 though :-) I'll add an MIT license file soonish.

**Comment by artemislena** [comment]
T.: K, thx! ^^ (my main reason for wantinga fork this one's #18, anyway, I'll just wait until ya add the license file then, Ig)

**Comment by Goctionni** [comment]
That will be one of the things im changing in the new version for sure. Kind of ashamed I let that one by the wayside :-(

**Comment by Goctionni** [comment]
License file has been added 👍
